

package com.design;

import java.io.File;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.UIManager;

import com.beans.InstanceBean;
import com.instance.ObjectFactory;
import com.utils.ClassFinder;
import com.utils.Utilities;

/**
 * 
 * @author __USER__
 */
public class Homepage extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Utilities tools;

	
	public Homepage() {
		try {
			String inf = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";

			UIManager.setLookAndFeel(inf);

		} catch (Exception e) {
			e.printStackTrace();
		}
		initComponents();
		init();
	}
	
	private void init() {
		// TODO Auto-generated method stub
		tools = new Utilities();
		InstanceBean instanceBean = new InstanceBean();
		ObjectFactory objectFactory = new ObjectFactory();
		tools.setInstanceBean(instanceBean);
		tools.setObjectFactory(objectFactory);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaMsg = new javax.swing.JTextArea();
		btnFindClasses = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtaClassLst = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		btnImae = new javax.swing.JButton();
		jtaStoredInstances = new javax.swing.JTextArea();
		lblImg = new javax.swing.JLabel();
		btnSend = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		btnQuit = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();

		setDefaultCloseOperation(3);
		getContentPane().setLayout(null);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Search Classes "));
		jPanel1.setLayout(null);

		jLabel1.setText("Enter the package(e.g. com.xxx.xxx):");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(20, 20, 220, 14);

		//jtaMsg.setText("com.testing.classes");
		jtaMsg.setColumns(20);
		jtaMsg.setRows(3);
		jScrollPane1.setViewportView(jtaMsg);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(20, 40, 230, 72);

		btnFindClasses.setText("Find Classes");
		btnFindClasses.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnFindClassesActionPerformed(evt);
			}
		});
		jPanel1.add(btnFindClasses);
		btnFindClasses.setBounds(20, 130, 170, 23);

		jtaClassLst.setColumns(20);
		jtaClassLst.setRows(4);
		jScrollPane2.setViewportView(jtaClassLst);
		jtaClassLst.setEditable(false);
		jtaClassLst.setLineWrap(true);
		jPanel1.add(jScrollPane2);
		jScrollPane2.setBounds(20, 190, 230, 90);

		jLabel2.setText("Identified Classes:");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(30, 170, 150, 14);

		getContentPane().add(jPanel1);
		jPanel1.setBounds(20, 70, 280, 300);

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Instance Generation"));
		jPanel2.setLayout(null);

		btnImae.setText("Generate Instance");
		btnImae.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGenerateInstanceActionPerformed(evt);
			}
		});
		jPanel2.add(btnImae);
		btnImae.setBounds(100, 30, 160, 23);

		
		JScrollPane jspIns = new javax.swing.JScrollPane();
		jtaStoredInstances.setColumns(20);
		jtaStoredInstances.setRows(4);
		jspIns.setViewportView(jtaStoredInstances);
		jtaStoredInstances.setEditable(false);
		jtaStoredInstances.setLineWrap(true);
		jPanel2.add(jspIns);
		jspIns.setBounds(10, 80, 350, 140);
		
		lblImg.setText("Generated Instances stored in");
		jPanel2.add(lblImg);
		lblImg.setBounds(10, 10, 260, 120);

		btnSend.setText("Finding Method Calls");
		btnSend.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnFindingMethodCallsActionPerformed(evt);
			}
		});
		jPanel2.add(btnSend);
		btnSend.setBounds(10, 230, 230, 23);

		getContentPane().add(jPanel2);
		jPanel2.setBounds(320, 70, 390, 300);

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel5.setForeground(new java.awt.Color(51, 51, 255));
		jLabel5.setText("Instance Generator");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(230, 14, 700, 30);

		btnQuit.setText("Exit");
		btnQuit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitActionPerformed(evt);
			}
		});
		getContentPane().add(btnQuit);
		btnQuit.setBounds(630, 390, 75, 23);

		jPanel3.setLayout(null);
		getContentPane().add(jPanel3);
		jPanel3.setBounds(0, 0, 740, 430);

		setSize(740, 460);
		setTitle("Instance Generator::");
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void btnFindingMethodCallsActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String recvname=jtaStoredInstances.getText();
		if(recvname!=null && recvname.compareTo("") == 0){
			JOptionPane.showMessageDialog(null, "Please generate the instances.");
		}else{
			MethodDesign methodDesign = tools.getObjectFactory().createMethodDesignObjects();
			methodDesign.searchMethodCalls(tools);
			
		}
	}

	private void btnGenerateInstanceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String classes = jtaClassLst.getText();
		
		if(classes.compareTo("") == 0){
			JOptionPane.showMessageDialog(null, "Please list out the java classes before generating instance.");
		}else{
			
			jtaStoredInstances.append("InstanceBean.class contains list of classes.\n");
			
			tools.generateAdequateInstance(jtaStoredInstances);
			
		}
		
			
	}

	private void btnFindClassesActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (valid()) {
			String packageName = jtaMsg.getText();
			String scannedPath = packageName.replace(".", "/");
			File file = new File("src/"+scannedPath);
			System.out.println("dir:"+file.isDirectory());
			
			File[] lst = file.listFiles();
			
			System.out.println(lst.length);
			
			
			List<Class<?>> classes = ClassFinder.findClasses(packageName);
			
			for (int i = 0; i < classes.size(); i++) {
				Class<?> class1 = classes.get(i);
				
				System.out.println(class1.getName());
				jtaClassLst.append((i + 1)+"."+class1.getName() + "\n");
			}
			
			tools.storeClasses(classes);
			
		}
	}

	
	private boolean valid() {
		// TODO Auto-generated method stub
		if (jtaMsg.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Enter the java package name.");
			return false;
		}

		return true;
	}

	int[] encint;
	String path;
	String embpath;
	String enmsg;
	
	private javax.swing.JButton btnImae;
	private javax.swing.JButton btnQuit;
	private javax.swing.JButton btnFindClasses;
	private javax.swing.JButton btnSend;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jtaClassLst;
	private javax.swing.JTextArea jtaMsg;
	private javax.swing.JLabel lblImg;
	private javax.swing.JTextArea jtaStoredInstances;
	// End of variables declaration//GEN-END:variables

}